version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.app:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: kk221b
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

volumes:
  postgres_data:
